name: health_alarm_app
description: "Health & Talking Alarm App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_tts: ^3.8.5
  android_alarm_manager_plus: ^3.0.4
  flutter_foreground_task: ^6.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.1.1
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/yoga/
